name: Node.js CI

on:
  push:
    branches: [ "main" ]
 

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo rm -rf /var/www/html/*
    - run: sudo cp -r /home/ubuntu/actions-runner/_work/myproject/myproject/dist/* /var/www/html/
    - run: sudo service apache2 restart    

